#!/bin/sh

## Production webserving!
# Differences are:
# - We serve the optimized JS blob (which we build prior to serving.)
# - We server pre-gzipped versions of everything and we keep'em in memory.
# - We let browsers cache our HTML and JS blobs for a bit!
# - We bind to port 2080 and assume you will iptables port 80 to that.
#    Allegedly something like this will work:
#    iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 2080
#
# Things that should not be different:
# - Caching of database requests.  We keep this the same to avoid ugly
#    surprises in production and because my local machine is more memory laden
#    than the current production VM anyways.
#
# Things you probably want to be doing, though:

# Build optimized JS blob
cd client
./optibuild

# Run production web server
cd ../server/lib
NODE_ENV=production node r.js arbpl/cmdline.js web
